-- 코드를 입력하세요
-- 총 주문량 > 3000
-- 주 성분 = 과일
-- 아이스크림의 맛
SELECT T2.FLAVOR
FROM FIRST_HALF T1,
    ICECREAM_INFO T2
WHERE T1.FLAVOR = T2.FLAVOR
AND TOTAL_ORDER > 3000
AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;
