# -- 코드를 입력하세요
# -- 제목, 게시글ID, 댓글ID, 댓글작성자, 댓글 내용, 댓글 작성일
# SELECT T1.TITLE,
#     T1.BOARD_ID,    
#     T2.REPLY_ID,
#     T2.WRITER_ID,
#     T2.CONTENTS,
#     DATE_FORMAT(T2.CREATED_DATE , '%Y-%m-%d') AS CREATED_DATE 
# FROM USED_GOODS_BOARD T1, USED_GOODS_REPLY T2
# WHERE T1.BOARD_ID = T2.BOARD_ID
# AND T1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
# AND T2.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
# ORDER BY T2.CREATED_DATE, T1.WRITER_ID;

SELECT
  B.TITLE,
  B.BOARD_ID,
  R.REPLY_ID,
  R.WRITER_ID,
  R.CONTENTS,
  DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
  ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;